<grammar> ::= <selection-statement>
<selection-statement> ::= if(_<condition>_){_<statement>_}_else{_<statement>_}
<statement> ::= <terminal-func>
              | <selection-statement>
<terminal-func> ::= moveUp
                  | moveDown
                  | moveLeft
                  | moveRight
                  | moveNeutral
<condition> ::= <boolean-func>
              | <boolean-func>_<boolean-operator>_<boolean-func>
              | <number-func>_<number-operator>_<number>
<boolean-func> ::= isJunction
<boolean-operator> ::= and
                     | or
<number-func> ::= getDistanceToClosestNonEdibleGhost
<number-operator> ::= EQ
                    | NE
                    | LT
                    | GT
                    | LE
                    | GE
<number> ::= 0
           | <nonzero-digit><digit-sequence>
<digit-sequence> ::= 
                   | <digit>
                   | <digit><digit-sequence>
<digit> ::= 0
          | <nonzero-digit>
<nonzero-digit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9