<grammar> ::= <selection-statement>
<selection-statement> ::= if(_<condition>_){_<statement>_}_else{_<statement>_}
                        | if(_<condition>_){_<statement>_}
<statement> ::= <terminal-func>
              | <selection-statement>
<terminal-func> ::= getDirectionTowardsClosestPill
                  | getDirectionAwayFromClosestNonEdibleGhost
                  | getDirectionTowardsClosestEdibleGhost
                  | getDirectionTowardsClosestPowerPill
				  | <simpleMoves>
<condition> ::= <boolean-func>
              | <boolean-func>_<boolean-operator>_<boolean-func>
              | <number-func>_<number-operator>_<number>
<boolean-func> ::= <boolean-api>
                 | !_<boolean-api>
<boolean-api> ::= isJunction
<boolean-operator> ::= and
                     | or
<number-func> ::= getDistanceToClosestNonEdibleGhost
                | getDistanceToClosestNonEdibleGhostUp
                | getDistanceToClosestNonEdibleGhostDown
                | getDistanceToClosestNonEdibleGhostLeft
                | getDistanceToClosestNonEdibleGhostRight
                | getDistanceToClosestEdibleGhost
                | getDistanceToClosestEdibleGhostUp
                | getDistanceToClosestEdibleGhostDown
                | getDistanceToClosestEdibleGhostLeft
                | getDistanceToClosestEdibleGhostRight
                | getNumberOfActivePowerPills
                | getDistToClosestPillUp
                | getDistToClosestPillDown
                | getDistToClosestPillLeft
                | getDistToClosestPillRight
                | getDistToClosestPill
                | getDistToClosestPowerPill
                | getDistToClosestPowerPillUp
                | getDistToClosestPowerPillDown
                | getDistToClosestPowerPillLeft
                | getDistToClosestPowerPillRight
                | getClosestJunctionExitsNumberUp
                | getClosestJunctionExitsNumberDown
                | getClosestJunctionExitsNumberLeft
                | getClosestJunctionExitsNumberRight
                | getDistanceToClosestJunctionUp
                | getDistanceToClosestJunctionDown
                | getDistanceToClosestJunctionLeft
                | getDistanceToClosestJunctionRight
                | getClosestNonEdibleGhostDistanceToClosestJunctionUp
                | getClosestNonEdibleGhostDistanceToClosestJunctionDown
                | getClosestNonEdibleGhostDistanceToClosestJunctionLeft
                | getClosestNonEdibleGhostDistanceToClosestJunctionRight
                | getClosestEdibleGhostDistanceToClosestJunctionUp
                | getClosestEdibleGhostDistanceToClosestJunctionDown
                | getClosestEdibleGhostDistanceToClosestJunctionLeft
                | getGeometricMeanDistanceToNonEdibleGhosts
                | getGeometricMeanDistanceToEdibleGhosts
<number-operator> ::= EQ
                    | NE
                    | LT
                    | GT
                    | LE
                    | GE
<simpleMoves> ::= moveUp
                | moveDown
                | moveLeft
                | moveRight
<number> ::= 0
           | <nonzero-digit>
           | <nonzero-digit><digit>
           | <nonzero-digit><digit><digit>
           | <nonzero-digit><digit><digit><digit>
           
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

<nonzero-digit> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
